config/routes.rb
Rails.application.routes.draw do
  root 'trips#index'
  
  resources :trips do
    resources :locations
  end
  
  resources :locations do
    resources :addresses
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :location, dependent: :destroy
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :trip
	has_one :address, dependent: :destroy

end

app/models/trip.rb
class Trip < ActiveRecord::Base
	has_many :locations, dependent: :destroy
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_location
  before_action :set_address, only: [:edit, :show, :update, :destroy]

  def edit
  end

  def update
    if @address.update(address_params)
      redirect_to trip_location_path(@location.trip_id, @location)
    else
      #TODO make a flash message
      render :edit
    end
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @location.address = @address
    if @location.address.save
      redirect_to trip_location_path(@location.trip_id, @location)
    else
      #TODO make a flash message
      render :new
    end
  end

  private
    def set_location
      @location = Location.find(params[:location_id])
    end

    def set_address
      @address = Address.find(params[:id])
    end

    def address_params
      params.require(:address).permit(:country, :city)
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :location, only: [:edit, :show, :update, :destroy]
  before_action :trip, only: [:index, :show, :new, :create]
  def index
    @locations = Location.all
  end

  def show
  end

  def edit
  end

  def update
    if @location.update(location_params)
      redirect_to location_path(@location)
    else
      #TODO make a flash message
      render :edit
    end
  end

  def new
    @location = Location.new
  end

  def create
    @location = @trip.locations.new(location_params)
    if @location.save
      redirect_to trip_location_path(@trip, @location)
    else
      #TODO make a flash message
      render :new
    end
  end

  def destroy
    if @location.destroy
      redirect_to locations_path
    else
      #flash error message
      redirect_to locations_path
    end
  end

  private
    def trip
      @trip = Trip.find(params[:trip_id])
    end

    def location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:place, :trip_id)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
	before_action :trip, only: [:edit, :show, :update, :destroy]

  def index
  	@trips = Trip.all
  end

  def show
  end

  def edit
  end

  def update
  	if @trip.update(trip_params)
  		redirect_to trip_path(@trip)
  	else
  		#TODO make a flash message
  		render :edit
  	end
  end

  def new
  	@trip = Trip.new
  end

  def create
  	@trip = Trip.new(trip_params)
  	if @trip.save
  		redirect_to trips_path
  	else
  		#TODO make a flash message
  		render :new
  	end
  end

  def destroy
  	if @trip.destroy
  	redirect_to trips_path
  	else
  		#flash error message
  		redirect_to trip_path
  	end
  end

  private

  	def trip
  		@trip = Trip.find(params[:id])
  	end

  	def trip_params
  		params.require(:trip).permit(:name, :info, :date)
  	end
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/addresses/_form.html.erb
<%= form_for [@location, @address] do |f| %>
	<%= f.label :country %>
	<%= f.text_field :country %>

  <%= f.label :city %>
	<%= f.text_field :city %>

	<%= f.submit %>

<% end %>

app/views/addresses/edit.html.erb
<h1>Edit address for <%=@location.place %></h1>

<%= render(partial: 'form') %>

app/views/addresses/new.html.erb
<h1>Address for <%= @location.place %></h1>

<%= render(partial:'form') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TripTrackr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for [@trip, @location] do |f| %>
	<%= f.label :place %>
	<%= f.text_field :place %>

	<%= f.submit %>

<% end %>

app/views/locations/edit.html.erb
<h1>Editing: <%= @location %></h1>

<%= render(partial:'form') %>

app/views/locations/index.html.erb
 <h1>All Locations</h1>
<br />

<% if @locations.any? %>
  <ul>
    <% @locations.each do |location| %>
    	<li>
        <%= link_to location.place, trip_location_path(@trip, location) %>
    	</li>
    <% end %>
  </ul>
<% else %>
  <h3>No Locations found. Please create one.</h3>
<% end %>

<%= link_to 'Back', trip_path(@trip) %>

<%= link_to 'New Locations', new_trip_location_path %> 

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render(partial:'form') %>

app/views/locations/show.html.erb
<h1>Location of: <%= @trip.name %></h1>

<h1><%= @location.place%> </h1>



<% if @location.address.nil? %>
  <h4>No Address Found Please Add One</h4>
  <%= link_to 'Add Address', new_location_address_path(@location) %>
<% else %>
  <h4>Address</h4>
  <p>Country: <%= @location.address.country %></p>
  <p>City: <%= @location.address.city %></p>
  <%= link_to 'Edit Address', edit_location_address_path(@location, @location.address) %>
<% end %>

<%= link_to 'Back', trip_locations_path(@trip) %>

app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :info %>
	<%= f.text_field :info %>
	
	<%= f.label :date %>
	<%= f.text_field :date %>
	<%= f.submit %>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip: <%= @trip.name %></h1>

<%= render(partial: 'form') %>

app/views/trips/index.html.erb
<h1>All Trips</h1>
<br />

<% if @trips.any? %>
	<ul>
	<% @trips.each do |trip| %>
	<li>
		<%= link_to trip.name, trip_path(trip) %>
	</li>
	<% end %>
	</ul>
<% else %>
		<h3>No trips found. Please create one.</h3>
<% end %>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>Create a New Trip</h1>

<%= render(partial: 'form') %>

app/views/trips/show.html.erb
<h1><%= @trip.name %> Info:</h1>
<br />
<h3>
	Description: <%= @trip.info %>
</h3>

<h2>
	Date: <%= @trip.date %>
</h2>

<%= link_to 'All Locations', trip_locations_path(@trip) %>

<%= link_to 'Edit', edit_trip_path(@trip) %>

<%= link_to 'Delete', trip_path(@trip), method: :delete %>

<%= link_to 'All Trips', trips_path %>